Algoritmo "Aula04-exercícios"
// Disciplina   : [Linguagem e Lógica de Programação]
Var
nome: caractere
peso, altura, imc: real
Inicio

   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Digite seu peso: ")
   leia(peso)
   escreva("Digite sua altura: ")
   leia(altura)
   
   escreval("Nome: ",nome)
   escreval("Peso: ",peso)
   escreval("Altura: ",altura)
   imc <- peso/(altura*altura)
   escreval("IMC: ",imc)
   



Fimalgoritmo